apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:    
    path: /tmp/data

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  awsElasticBlockStore:    
    volumeID: <volume-id>
    fsType: ext4

# kubectl get pv
# kubectl create -f     