apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-deploy-new
  name: my-deploy-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deploy-new
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-deploy-new
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
status: {}
