apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
spec: 
  securityContext:
    runAsUser: 1000
  containers:
    - name: simple-webapp-color
      image: simple-webapp-color
      commands: ["sleep", "3600"]

# security context at pod level  