apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
spec: 
  containers:
    - name: simple-webapp-color
      image: simple-webapp-color
      commands: ["sleep", "3600"]
      securityContext:
        runAsUser: 1000
        capabilities: # capabilities are only supported at container level
          add: ["MAC_ADMIN"]

# security context at container level          
# The User ID defined in the securityContext of the container overrides the User ID in the POD.