apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: math-add-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      completions: 3
      parallelism: 3
      template:
        containers:
          - name: math-add
            image: ubuntu
            command: ['expr', '3', '+', '5']
        restartPolicy: Never      