apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: test-job
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: test-job
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: nginx
            name: test-job
            resources: {}
          restartPolicy: OnFailure
  schedule: 30 21 * *
status: {}
