apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels:
    app: nginx
    tier: front-end
spec:
  containers:
    - name: nginx
      image: nginx 
      livenessProbe:
        exec:
          command:
            - cat
            - /api/is_ready

